# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jorge Antônio da Silva
email: contato@jorgeants.com
description: > # this means to ignore newlines until "baseurl:"
  Full-stack developer, trabalha com desenvolvimento para a web desde 2008.
baseurl: ""
url: "http://jorgeants.com"
twitter_username: jorgeants
github_username:  jorgeants

# Build settings
markdown: kramdown

exclude: ['package.json', 'src', 'node_modules']
