# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jorge Antônio da Silva
email: contato@jorgeants.com
description: > # this means to ignore newlines until "baseurl:"
  Sempre muito curioso e empreendedor, comecei a programar com 16 anos.
  Hoje, além de desenvolvedor sou sócio e propretário da React,
  onde gerencia o time de desenvolvimento.
# description: > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jorgeants.com" # the base hostname & protocol for your site
twitter_username: jorgeants
github_username:  jorgeants

# Build settings
markdown: kramdown
